In [9]:
import pandas as pd

In [10]:
table = pd.read_csv("resources/titanic.csv")

In [11]:
table.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
df2 = pd.DataFrame.from_dict({"a": [1, 2, 454545], "columns": ["a", "b", "c"], "index" :["a", "b", "c"]})

In [13]:
df2.head()

        a columns index
0       1       a     a
1       2       b     b
2  454545       c     c

In [14]:
df2.head()

        a columns index
0       1       a     a
1       2       b     b
2  454545       c     c

In [15]:
df2.to_csv("resources/test.csv")

In [19]:
table

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [17]:
table.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [20]:
b = ['Age', 'Fare', 'Pclass',"Name"]
table[b]

      Age     Fare  Pclass                                               Name
0    22.0   7.2500       3                            Braund, Mr. Owen Harris
1    38.0  71.2833       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    26.0   7.9250       3                             Heikkinen, Miss. Laina
3    35.0  53.1000       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4    35.0   8.0500       3                           Allen, Mr. William Henry
..    ...      ...     ...                                                ...
886  27.0  13.0000       2                              Montvila, Rev. Juozas
887  19.0  30.0000       1                       Graham, Miss. Margaret Edith
888   NaN  23.4500       3           Johnston, Miss. Catherine Helen "Carrie"
889  26.0  30.0000       1                              Behr, Mr. Karl Howell
890  32.0   7.7500       3                                Dooley, Mr. Patrick

[891 rows x 4 columns]