In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../resources/data.csv', sep='|')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    str
 3   occupation  943 non-null    str
 4   zip_code    943 non-null    str
dtypes: int64(2), str(3)
memory usage: 37.0 KB

In [5]:
df.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [6]:
df.describe()

          user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

In [7]:
ls = ["age","occupation"]
df[ls]

     age     occupation
0     24     technician
1     53          other
2     23         writer
3     24     technician
4     33          other
..   ...            ...
938   26        student
939   32  administrator
940   20        student
941   48      librarian
942   22        student

[943 rows x 2 columns]